public OL_ResultScope getScope(){return OL_ResultScope.ENERGYMODEL;}
public J_RapidRunData getRapidRunData(){return v_rapidRunData;}
public J_LiveData getLiveData(){return v_liveData;}
public J_RapidRunData getPreviousRapidRunData(){return v_previousRunData;}
public J_ActiveAssetData getActiveAssetData(){return v_activeAssetData;}
public double getDeliveryCapacity_kW(){return f_getTopLevelGridCapacity_kW();}
public double getFeedinCapacity_kW(){return f_getTopLevelGridCapacity_kW();}
public boolean getDeliveryCapacityKnown(){return false;}
public boolean getFeedinCapacityKnown(){return false;}