public ZeroAccumulator getAcc_dailyAverageHeatPumpElectricityConsumption_kW() { return acc_dailyAverageHeatPumpElectricityConsumption_kW; }
public ZeroAccumulator getAcc_dailyAverageElectricVehicleConsumption_kW() { return acc_dailyAverageElectricVehicleConsumption_kW; }
